### ISSUE TITLE
About org file export operation problem.

### ISSUE THREAD

**Issue by linweiyang** [ztlevi/doom-config#5]
export the org file to html file, the following error is happen:

**file-name-extension: Wrong type argument: stringp, nil**

How to fix it ?

**Comment by ztlevi** [comment]
Better to use pandoc, e.g. C-c C-e p 4.

This is probly due to the version of org. It broke up for some reason during the org upgradation. I was able to solve this similar problem couple times but it's totally not worth the time. Although I don't really have the backtrace of the bug. You can do `M-x toggle-debug-on-error` and see the backtrace.
 
Just install pandoc and use it.

**Comment by linweiyang** [comment]
The error is happen when the following function is executed:
+my/check-minified-file.

Inside this function, "buffer-file-name" is "nil", so (file-name-extension (buffer-file-name)) return error message "file-name-extension: Wrong type argument: stringp, nil".

**Comment by linweiyang** [comment]
I add codes to **autoload/misc.el** file to check if buffer-file-name is nil, the problem seems to be solved.

**(defun +my/check-minified-file ()
  (and
   (not (if (buffer-file-name)
            (member (file-name-extension (buffer-file-name))
                    '("org" "md" "markdown" "txt" "rtf"))))
   (cl-loop for i from 1 to (min 30 (count-lines (point-min) (point-max)))
            if (> (get-nth-line-length i) 1000)
            return t
            finally return nil)))**

**Comment by ztlevi** [comment]
Great catch up! Thanks.
