### ISSUE TITLE
Dark Theme Support

### ISSUE THREAD

**Issue by nehcuh** [ztlevi/doom-config#9]
Sorry to disturb,

Once I've tried another dark theme, the cursor and status bar displayed abnormal. 
The figure showed is the case while I'm using theme "doom-ayu-mirage".
So, is there something I should modify if I want to try dark theme?

![QQ截图20210605174151](https://user-images.githubusercontent.com/36597254/120887431-637a9680-c625-11eb-9af7-e2b58df87b19.png)

**Comment by ztlevi** [comment]
The current ui setup is fine. You need to change the actual config here https://github.com/ztlevi/doom-config/blob/master/+ui.el#L8, rather than try the theme with spc h t.

The reason is here. https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-ayu-mirage-theme.el#L73
https://github.com/ztlevi/doom-config/blob/master/+ui.el#L69
The ui-line didn’t apply to the bg-alt for some reason.
